# GitLab CI/CD 配置 - 自动构建 Windows EXE

stages:
  - build

# Android 监控版本
build-android:
  stage: build
  tags:
    - windows  # 需要 Windows Runner
  
  before_script:
    - python --version
    - python -m pip install --upgrade pip
    - pip install -r requirements_windows.txt
    - pip install pyinstaller
  
  script:
    - pyinstaller build_android.spec
  
  artifacts:
    name: "Android性能监控-Windows-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist/Android性能监控.exe
    expire_in: 30 days
  
  only:
    - main
    - master
    - tags

# 跨平台统一版本
build-unified:
  stage: build
  tags:
    - windows  # 需要 Windows Runner
  
  before_script:
    - python --version
    - python -m pip install --upgrade pip
    - pip install -r requirements_windows.txt
    - pip install pyinstaller
  
  script:
    - pyinstaller build_unified.spec
  
  artifacts:
    name: "跨平台性能监控-Windows-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist/跨平台性能监控.exe
    expire_in: 30 days
  
  only:
    - main
    - master
    - tags
