name: Build Windows EXE

on:
  # 推送到主分支时自动构建
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android Monitor (Windows)
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_windows.txt
        pip install pyinstaller
    
    - name: Build Android Monitor EXE
      run: |
        pyinstaller build_android.spec
    
    - name: Upload Android Monitor EXE
      uses: actions/upload-artifact@v3
      with:
        name: Android性能监控-Windows
        path: dist/Android性能监控.exe
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Android性能监控.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-unified:
    name: Build Unified Monitor (Windows)
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_windows.txt
        pip install pyinstaller
    
    - name: Build Unified Monitor EXE
      run: |
        pyinstaller build_unified.spec
    
    - name: Upload Unified Monitor EXE
      uses: actions/upload-artifact@v3
      with:
        name: 跨平台性能监控-Windows
        path: dist/跨平台性能监控.exe
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/跨平台性能监控.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
